name: Deploy Backend (Test)

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Split backend subtree
        run: |
          git subtree split --prefix consultia/backend -b heroku-deploy

      - name: Push to Heroku (test app)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/medberos-tima-test.git heroku-deploy:main --force
          

      - name: Cleanup temp branch
        run: git branch -D heroku-deploy